# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'HeadSwipe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeadSwipe
  pod 'SwiftSoup', '~> 1.6'

  target 'HeadSwipeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeadSwipeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
